// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 
        'views/layout', 
        'routes', 
        'controllers/tag_controller',
        'controllers/filter_controller',
        'controllers/link_form_controller'], function(Chaplin, Layout, routes, TagController,FilterController, FormController) {
  'use strict';

  var LinksyApp;
  return LinksyApp = (function(_super) {

    __extends(LinksyApp, _super);

    function LinksyApp() {
      return LinksyApp.__super__.constructor.apply(this, arguments);
    }

    LinksyApp.prototype.title = 'Chaplin Example Application';

    LinksyApp.prototype.initialize = function() {
      LinksyApp.__super__.initialize.apply(this, arguments);
      
      this.initMediator();
      this.initDispatcher();
      this.initLayout();
      
      this.initControllers();
      
      var routerOptions = {
                    pushState:false
                };
                // Register all routes and start routing
      this.initRouter(routes, routerOptions);
      return typeof Object.freeze === "function" ? Object.freeze(this) : void 0;
    };

    LinksyApp.prototype.initLayout = function() {
      console.log("here")
      return this.layout = new Layout({
        title: this.title
      });
    };

    LinksyApp.prototype.initControllers = function() {
    
        app.layout.form = new FormController();
        app.layout.tags = new TagController();
        app.layout.currentFilter = new FilterController();
        return;
    };

    LinksyApp.prototype.initMediator = function() {
      Chaplin.mediator.user = null;
      return Chaplin.mediator.seal();
    };

    return LinksyApp;

  })(Chaplin.Application);
});
