// Generated by CoffeeScript 1.3.3

define(function() {
  'use strict';
  return function(match) {
    match('login', 'linksy#login');
    match('all', 'linksy#show');
    match('show/:tag', 'linksy#showTag');
    return match('all', 'linksy#show');
  };
});
