// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/tag', 'views/form_view'], function(Chaplin, TagCollection, FormView) {
  'use strict';

  var FormController;
  return FormController = (function(_super) {

    __extends(FormController, _super);

    function FormController() {
      return FormController.__super__.constructor.apply(this, arguments);
    }

    FormController.prototype.initialize = function(params) {
      console.log("FormController.init");  
      FormController.__super__.initialize.apply(this, arguments);
      return this.view = new FormView();
    };

    return FormController;

  })(Chaplin.Controller);
});
