// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/tag', 'views/tag_view'], function(Chaplin, TagCollection, TagView) {
  'use strict';

  var TagController;
  return TagController = (function(_super) {

    __extends(TagController, _super);

    function TagController() {
      return TagController.__super__.constructor.apply(this, arguments);
    }


    TagController.prototype.initialize = function(params) {
    
      console.log("TagController.init");  
      TagController.__super__.initialize.apply(this, arguments);
      this.collection = new TagCollection();
      
      var that = this;
      return that.view = new TagView({
                collection: that.collection
             });
    };

    return TagController;

  })(Chaplin.Controller);
});
