// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'text!templates/links.hbs'], function(View, template) {
  'use strict';

  var LinksView;
  return LinksView = (function(_super) {

    __extends(LinksView, _super);

    function LinksView() {
      return LinksView.__super__.constructor.apply(this, arguments);
    }

    LinksView.prototype.template = template;
    LinksView.prototype.initialize = function(){
        LinksView.__super__.initialize.apply(this, arguments);
        console.log("linksview.initialize");
        console.log(this);
    };

   // template = null;

    LinksView.prototype.className = 'links';

    LinksView.prototype.container = '#links-container';

    LinksView.prototype.autoRender = true;

    return LinksView;

  })(View);
});
