// Generated by CoffeeScript 1.3.3

define(['underscore', 'chaplin', 'models/link_collection'], function(_, Chaplin, LinkCollection) {
  'use strict';

  var utils;
  utils = Chaplin.utils.beget(Chaplin.utils);
  
  
  _(utils).extend({
    LinksColl : new LinkCollection()
  });
  return utils;
});
